# Generated by Django 4.1.4 on 2022-12-15 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/profile/')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(max_length=128)),
                ('age', models.IntegerField(default=18)),
                ('employee_id', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees_employee',
                'ordering': ('name', '-salary'),
            },
        ),
    ]
