# Generated by Django 4.1.4 on 2022-12-15 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('house_number', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
                'db_table': 'houses_house',
                'ordering': ('house_number', 'name'),
            },
        ),
    ]
