# Generated by Django 4.1.4 on 2023-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
