# Generated by Django 4.1.4 on 2022-12-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(default='MBID0', max_length=30),
        ),
    ]
